### ISSUE TITLE
Remove your AWS Secret Keys from your repo :)

### ISSUE THREAD

**Issue by nathan-grant** [ErikSoerup/BDO-ideportal#1]
FYI the S3 credentials you have checked it are valid, you should probably rotate the ones in use and not check those in somewhere public.

**Comment by nathan-grant** [comment]
Looks like that file is really old, so I assume those credentials have been rotated, sorry to bug you.

**Comment by hendragunz** [comment]
Yes this is old application, too old. Not sure if these AWS key still works
